name: studyspot_64
description: ""
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  google_fonts: ^6.1.0
  audioplayers: ^6.0.0

  shared_preferences: ^2.2.2
  camera: ^0.11.3
  mobile_scanner: ^5.2.3
  path_provider: ^2.1.5
  path: ^1.9.1
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.1
  image_picker: ^1.2.1
  firebase_storage: ^12.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "AppIcons/playstore.png"
  web:
    generate: true
    image_path: "AppIcons/playstore.png"
    background_color: "#0175C2"
    theme_color: "#0175C2"




flutter:
  uses-material-design: true
  assets:
    - AppIcons/intro.png
    - assets/images/
    - assets/images/