name: studyspot_64
description: ""
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  cupertino_icons: ^1.0.6
  # Για τοπική αποθήκευση δεδομένων (Persistence)
  shared_preferences: ^2.2.2
  # Για την πλοήγηση (Bottom Navigation Bar)
  persistent_bottom_nav_bar: ^5.0.2
  # Για το QR Code scanning
  qr_code_scanner: ^1.0.1
  # Για ηχητικές ειδοποιήσεις
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true